services:

    email_sender:
        class: JGI\AppBundle\Service\EmailSender
        arguments:
            - @mailer
            - @templating
            - %mailer_from%
            - %mailer_recipients%

    twig.app_extension:
        class: JGI\AppBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }

    scraper:
        class: JGI\AppBundle\Service\Scraper
        arguments:
            - @client

    client:
        class: Goutte\Client

    command.check:
        class: JGI\AppBundle\Command\CheckCommand
        arguments:
            - @email_sender
            - @scraper
            - %credentials%
            - @slackbot
        tags:
            - { name: console.command }

    slackbot:
        class: JGI\AppBundle\Service\SlackBot
        arguments:
            - @client
            - %slackurl%
